#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#ejemplo 0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597

pase = int(1)
primero = 0
segundo = 1
numeracion = int(1)

while pase != 0:
    resultado = primero + segundo
    if resultado < 4000000:
        resto = resultado % 2
        if resto == 0:
            print(numeracion,' - ',resultado)
        primero = segundo
        segundo = resultado
        numeracion += 1
    else:          
        pase = 0